// Policy texts copied from the previous site (kornu.se/policies/*).
// Paragraphs starting with "## " render as headings and "- " as list items.

export const privacyPolicyParagraphs: string[] = [
  "Senast uppdaterad: 21 september 2026",
  "Denna integritetspolicy beskriver hur Kör Nu Trafikskola (webbplatsen, vi) samlar in, använder och delar dina personuppgifter vid dina besök, när du använder våra tjänster eller köper från kornu.se (webbplatsen) eller på annat sätt kommunicerar med oss angående webbplatsen (tillsammans kallade tjänsterna). Användningen av du/dina (mfl.) i den här integritetspolicyn avser dig som användare av tjänsterna, oavsett om du är kund, webbplatsbesökare eller annan person som vi har samlat in uppgifter om enligt denna integritetspolicy.",
  "Vi rekommenderar att du läser denna integritetspolicy noggrant.",
  "## Ändringar av denna integritetspolicy",
  "Vi kan emellanåt uppdatera denna integritetspolicy, till exempel för att den ska överensstämma med nya rutiner eller på grund av andra driftmässiga, juridiska eller lagstiftningsmässiga skäl. Den reviderade integritetspolicyn kommer att publiceras på webbplatsen, vilket framgår av angivet datum vid “Senast uppdaterad”, samt vidta eventuella andra åtgärder som krävs enligt tillämplig lag.",
  "## Hur vi samlar in och använder personuppgifter",
  "För att tillhandahålla tjänsterna samlar vi in dina personuppgifter från en mängd olika källor enligt nedanstående beskrivning. Vilka uppgifter vi samlar in och använder varierar beroende på hur du interagerar med oss.",
  "Utöver de specifika ändamål som anges nedan kan vi använda de uppgifter vi samlat in om dig för att kommunicera med dig, tillhandahålla eller förbättra tjänsterna, uppfylla eventuella tillämpliga lagkrav, genomdriva eventuella tillämpliga användarvillkor för tjänsten samt för att skydda tjänsterna, våra rättigheter samt våra användares och andras rättigheter.",
  "## Vilka personuppgifter vi samlar in",
  "Vilka typer av personuppgifter vi samlar in om dig beror på hur du interagerar med vår webbplats och använder våra tjänster. När vi använder termen personuppgifter avser vi information som identifierar dig, rör dig, beskriver dig eller som på något sätt kan kopplas till dig. Avsnitten nedan beskriver de kategorier och specifika typer av personuppgifter vi samlar in.",
  "## Uppgifter vi samlar in direkt från dig",
  "Uppgifter som du själv skickar till oss via våra tjänster kan innefatta:",
  "- Kontaktuppgifter till exempel namn, adress, telefonnummer och e-postadress.",
  "- Orderinformation till exempel namn, faktureringsadress, leveransadress, betalningsbekräftelse, e-postadress och telefonnummer.",
  "- Kontoinformation till exempel användarnamn, lösenord, säkerhetsfrågor och annan information som används för att skydda ditt konto.",
  "- Kundsupportinformation Till exempel information du väljer att dela med dig av när du kommunicerar med oss, som när du skickar ett meddelande via tjänsterna.",
  "Vissa funktioner i tjänsterna kan kräva att du direkt ger oss viss information om dig själv. Du kan välja att inte dela med dig sådan information, men det kan i så fall bli omöjligt för dig att använda eller få tillgång till dessa funktioner.",
  "## Information vi samlar in om din användning",
  "Vi kan också automatiskt samla in viss information om din interaktion med tjänsterna (användningsdata). För detta ändamål kan vi använda cookies, pixlar och liknande tekniker (cookies). Användningsdata kan innehålla information om hur du kommer åt och använder vår webbplats och ditt konto, inklusive uppgifter om din enhet, webbläsare, nätverksanslutning, IP-adress och annan information om din interaktion med tjänsterna.",
  "## Information vi får från tredje part",
  "Vi kan till sist också erhålla information om dig från tredje part, inklusive från leverantörer och tjänsteleverantörer som kan samla in information för vår räkning, till exempel:",
  "- Företag som stödjer vår webbplats och våra tjänster, till exempel Shopify.",
  "- Våra betalningsbehandlare som samlar in betalningsinformation (t.ex. uppgifter om bankkonto, kredit- eller betalkort, faktureringsadress) i syfte att behandla din betalning för att kunna distribuera dina beställningar och leverera de produkter eller tjänster som du har efterfrågat, för att kunna fullgöra vårt kontrakt med dig.",
  "- När du besöker vår webbplats, öppnar eller klickar på e-postmeddelanden som vi skickar till dig eller interagerar med våra tjänster eller annonser kan vi eller tredje part som vi samarbetar med automatiskt samla in viss information med hjälp av onlinespårningstekniker som t.ex. pixlar, webb-beacons, SDK:er, tredjepartsbibliotek och cookies.",
  "All information vi får från tredje part kommer att behandlas i enlighet med denna integritetspolicy. Se även avsnittet nedan, Webbplatser som tillhör tredje part och länkar.",
  "## Hur vi använder dina personuppgifter",
  "- Tillhandahålla produkter och tjänster. Vi använder dina personuppgifter för att tillhandahålla dig tjänsterna för att kunna fullgöra vårt kontrakt med dig, inklusive för att behandla dina betalningar, distribuera dina beställningar, för att skicka meddelanden till dig relaterade till ditt konto, dina inköp, returer, byten eller andra transaktioner, för att skapa, underhålla och på annat sätt hantera ditt konto, för att ordna frakt, underlätta eventuella returer och byten och andra funktioner och funktioner relaterade till ditt konto. Vi kan också förbättra din shoppingupplevelse genom att göra det möjligt för Shopify att matcha ditt konto med andra Shopify-tjänster som du kan välja att använda. I så fall kommer Shopify att behandla dina uppgifter enligt sin integritetspolicy och konsumentskyddspolicy.",
  "- Marknadsföring och annonsering. Vi kan använda dina personuppgifter för marknadsförings- och reklamändamål, till exempel för att skicka marknadsföring, annonser och reklamkommunikation via e-post, sms eller vanlig post, och för att visa dig annonser för produkter eller tjänster. Detta kan inkludera att använda dina personuppgifter för att på ett bättre sätt kunna skräddarsy tjänsterna och annonseringen på vår webbplats och andra webbplatser. Om du är bosatt i EES är den rättsliga grunden för denna behandling av personuppgifter vårt berättigade intresse av att sälja våra produkter, enligt artikel 6 punkt 1f i GDPR.",
  "- Säkerhet och förebyggande av bedrägerier. Vi använder dina personuppgifter för att identifiera, undersöka eller vidta åtgärder avseende eventuell bedräglig, olaglig eller skadlig aktivitet. Om du väljer att använda tjänsterna och registrera ett konto är du ansvarig för att dina inloggningsuppgifter är säkra. Vi rekommenderar starkt att du inte delar ditt användarnamn, lösenord eller annan åtkomstinformation med någon annan. Om du tror att ditt konto har äventyrats, kontakta oss omedelbart. Om du är bosatt i EES är den rättsliga grunden för denna behandling av personuppgifter vårt berättigade intresse av att hålla vår webbplats säker för såväl dig som andra kunder, enligt artikel 6 punkt 1f i GDPR.",
  "- Kommunicera med dig och förbättra tjänsten. Vi använder dina personuppgifter för att erbjuda dig kundsupport och förbättra våra tjänster. Detta är ett berättigat intresse för oss för att vi ska kunna vara lyhörda för dig, för att tillhandahålla dig effektiva tjänster och för att upprätthålla vår affärsrelation med dig enligt artikel 6 punkt 1f i GDPR.",
  "## Cookies",
  "Liksom många andra använder vi cookies på vår webbplats. För närmare information om de cookies som vi använder för att driva vår butik med Shopify, se https://www.shopify.com/legal/cookies. Vi använder cookies för att driva och förbättra vår webbplats och våra tjänster (inklusive för att spara information om din aktivitet och dina inställningar), för att genomföra analyser och få bättre förståelse för hur användare interagerar med tjänsterna (som berör vårt berättigade intresse att administrera, förbättra och optimera tjänsterna). Vi kan också tillåta att tredje part och tjänsteleverantörer använder cookies på vår webbplats för att på ett bättre sätt kunna skräddarsy tjänsterna, produkterna och reklamen på vår webbplats och andra webbplatser.",
  "Att acceptera cookies automatiskt är standard i de flesta webbläsare, men du kan själv ändra inställningarna i din webbläsare så att cookies tas bort eller avvisas. Tänk på att din upplevelse kan påverkas negativt om du tar bort eller blockerar cookies, och dessutom kan vissa tjänster, till exempel vissa funktioner och allmän funktionalitet, sluta att fungera helt eller delvis. Det kan dessutom vara så att blockering av cookies inte helt förhindrar vår informationsdelning med tredje part, till exempel våra annonspartners.",
  "## Hur vi lämnar ut personuppgifter",
  "Under vissa omständigheter kan vi komma att överlämna dina personuppgifter till tredje part i syfte att fullgöra kontrakt, för berättigade ändamål och andra skäl som omfattas av denna integritetspolicy. Några exempel på sådana omständigheter:",
  "- Uppgifter kan delges leverantörer eller andra tredje parter som utför tjänster för vår räkning (t.ex. IT-förvaltning, betalningshantering, dataanalys, kundsupport, molnlagring, distribution och leverans).",
  "- Uppgifter kan delges företags- och marknadsföringspartners för att kunna leverera tjänster och reklam till dig. Våra affärs- och marknadsföringspartners kommer att använda dina uppgifter i enlighet med deras sekretessmeddelanden.",
  "- När du själv begär eller på annat sätt samtycker till att vi överlämnar vissa uppgifter till tredje part, till exempel för att leverera produkter till dig eller när du använder widgetar på sociala medier eller inloggningsbaserade integreringar, kan vi också komma att dela med oss av dina uppgifter.",
  "- Uppgifter kan delas med våra affiliates eller inom vår koncern som en del av våra berättigade intressen av att bedriva en framgångsrik verksamhet.",
  "- Uppgifter kan delas i samband med en affärshändelse, till exempel en fusion eller konkurs, i syfte att uppfylla tillämpliga rättsliga skyldigheter (till exempel som svar på förelägganden, beslut om husrannsakan), genomdriva tillämpliga användarvillkor och skydda och ta till vara tjänsterna, våra rättigheter samt våra användares och övriga personers rättigheter.",
  "Vi lämnar ut följande kategorier av personuppgifter och känslig personlig information om användare för syften som anges ovan i \"Så här samlar vi in och använder dina personuppgifter\" och \"Så här lämnar vi ut personuppgifter\":",
  "- Identifierare som t.ex. grundläggande kontaktuppgifter och viss order- och kontoinformation",
  "- Kommersiell information som t.ex. information om order, shopping och kundsupport",
  "- Internet- eller annan liknande nätverksaktivitet, t.ex. användningsdata",
  "- Geolokaliseringsdata, t.ex. platser som bestäms via en IP-adress eller andra tekniska metoder",
  "- Leverantörer och tredje parter som utför tjänster för vår räkning (t.ex. internetleverantörer, betalningsprocessorer, distributionspartners, kundsupportpartners och dataanalysleverantörer)",
  "- Affärs- och marknadföringspartners",
  "- Affiliates",
  "Vi varken använder eller avslöjar känsliga personuppgifter utan ditt samtycke eller för att kunna dra slutsatser om dig.",
  "Med ditt samtycke delar vi personuppgifter i syfte att genomföra reklam- och marknadsföringsaktiviteter enligt beskrivningen nedan.",
  "## Användargenererat innehåll",
  "Tjänsterna kan göra det möjligt för dig att publicera produktomdömen och annat användargenererat innehåll. Om du väljer att skicka användargenererat innehåll till någon offentlig del av tjänsterna kommer detta innehåll att vara offentligt och tillgängligt för alla.",
  "Vi kontrollerar inte vem som kommer att ha tillgång till den information som du väljer att göra tillgänglig för andra och kan inte säkerställa att de som har tillgång till sådan information kommer att respektera din integritet eller hålla den säker. Vi ansvarar inte för integriteten eller säkerheten avseende sådan information som du gör allmänt tillgänglig, och heller inte för om information som du delar med eller tar emot från tredje part är tillförlitlig, används eller missbrukas.",
  "## Webbplatser och länkar som tillhör tredje part",
  "Vår webbplats kan tillhandahålla länkar till webbplatser eller andra onlineplattformar som drivs av tredje part. Om du följer länkar till webbplatser som inte tillhör våra affiliates eller kontrolleras av oss, bör du läsa deras integritets- och säkerhetspolicyer och övriga regler och villkor. Vi garanterar inte och är inte ansvariga för integriteten eller säkerheten hos sådana webbplatser, inklusive huruvida informationen på dessa webbplatser är korrekt, fullständig och tillförlitlig. Information som du själv tillhandahåller på helt eller delvis allmänt tillgängliga platser, inklusive information som du delar på sociala nätverksplattformar tillhöriga tredje part, kan också ses av andra som använder tjänsterna och/eller de som använder dessa tredjepartsplattformar utan någon begränsning för hur den kan användas av oss eller tredje part. Enbart det faktum att vi inkluderar länkar av detta slag innebär inte att vi stödjer innehållet på sådana plattformar, och heller inte deras ägare eller verksamhet, utöver vad som uttryckligen klargörs i tjänsterna.",
  "## Uppgifter rörande barn",
  "Tjänsterna är inte avsedda att användas av barn, och vi samlar inte medvetet in personuppgifter om barn. Om ett barn som du är vårdnadshavare till har överlämnat sina personuppgifter till oss kan du kontakta oss via kontaktuppgifterna nedan för att begära att de raderas.",
  "Fram till det datum då denna integritetspolicy trädde i kraft känner vi inte till att vi har ”delat” eller ”sålt” (enligt de definitioner som används i tillämplig lagstiftning) personuppgifter avseende personer under 16 år.",
  "## Säkerhet för och lagring av dina uppgifter",
  "Observera att inga säkerhetsåtgärder är perfekta eller omöjliga att kringgå, och att vi inte kan garantera att säkerheten är perfekt. Eventuell information som du skickar till oss kan dessutom sakna skydd under överföringen. Vi rekommenderar att du inte använder osäkra metoder för att skicka känslig eller konfidentiell information till oss.",
  "Hur länge vi behåller dina personuppgifter beror på olika faktorer, till exempel om vi behöver dem för att hantera ditt konto, tillhandahålla tjänsterna, fullgöra rättsliga skyldigheter, lösa tvister eller genomdriva andra tillämpliga kontrakt och policyer.",
  "## Dina rättigheter",
  "Beroende på var du bor kan du ha vissa eller samtliga rättigheter nedan gällande dina personuppgifter. Dessa rättigheter är dock inte absoluta, utan det är möjligt att de endast gäller under vissa omständigheter, och lagen medger att vi då kan neka din begäran.",
  "- Rätt till tillgång/kännedom: Du kan ha rätt att begära tillgång till de personuppgifter som vi har om dig, inklusive information om hur vi använder och delar din information.",
  "- Rätt till radering: Du kan ha rätt att begära att vi raderar de personuppgifter vi innehar.",
  "- Rätt till korrigering: Du kan ha rätt att begära att vi korrigerar de personuppgifter vi innehar om de är felaktiga.",
  "- Rätt till portabilitet: Du kan under vissa omständigheter och med vissa undantag ha rätt att erhålla en kopia av de personuppgifter vi har om dig och att begära att vi överför dem till en tredje part.",
  "- Rätt att välja bort försäljning, delning eller riktad annonsering: Du kan ha rätt att instruera oss att inte ”sälja” eller ”dela” dina personuppgifter eller att ange att dina personuppgifter inte får användas för ändamål som anses vara ”riktad reklam”, enligt definitionen i tillämpliga integritetslagar. Om du besöker vår webbplats med GPC-signalen aktiverad (beroende på var du befinner dig) kommer vi automatiskt att tolka detta som en begäran om att neka “försäljning” eller “delning” av uppgifter för den enhet och webbläsare du använder för att besöka webbplatsen.",
  "- Begränsa behandling: Du kan ha rätt att begära att vi inte längre behandlar dina personuppgifter eller begränsar vår behandling av dem.",
  "- Återkalla samtycke: I de fall då vi förlitar oss på samtycke för att kunna behandla dina personuppgifter kan du ha rätt att återkalla ditt samtycke.",
  "- Överklagande: Om vi avslår din begäran kan du ha rätt att överklaga vårt beslut. Du kan göra det genom att svara på vårt meddelande om avslag.",
  "- Hantera kommunikationsinställningar: Vi kan skicka e-post med reklam till dig, och du kan välja att inte längre få sådan e-post genom att använda funktionen för att avsluta prenumerationen som finns i alla våra meddelanden till dig. Om du väljer att inte längre ta emot sådan e-post kan vi ändå skicka meddelanden till dig som inte innehåller reklam, till exempel information om ditt konto eller dina beställningar.",
  "Du kan utöva dessa rättigheter där så anges på vår webbplats eller genom att kontakta oss via nedanstående kontaktuppgifter.",
  "Din status hos oss påverkas inte av att du utövar dina rättigheter. Vi kan behöva samla in information från dig för att verifiera din identitet, till exempel din e-postadress eller kontoinformation, innan vi ger ett väl underbyggt svar på din begäran. Enligt tillämplig lagstiftning kan du utnämna en företrädare som kan framställa begäranden för din räkning för att utöva dina rättigheter. Innan vi godtar en sådan begäran från en representant måste denna representant förete bevis för att du har godkänt att de agerar för din räkning, och du kan också personligen behöva verifiera din identitet för oss. Vi kommer att besvara din begäran inom den tid som tillämplig lagstiftning specificerar.",
  "## Klagomål",
  "Om du har klagomål på hur vi behandlar dina personuppgifter, kontakta oss med hjälp av kontaktuppgifterna nedan. Om du inte är nöjd med hur vi handlagt ditt klagomål kan du, beroende på var du bor, ha rätt att överklaga vårt beslut genom att kontakta oss med hjälp av kontaktuppgifterna nedan. Du kan också välja att skicka ditt klagomål till Integritetsskyddsmyndigheten (IMY). För EES kan du hitta en lista över ansvariga tillsynsmyndigheter för dataskydd här.",
  "## Internationella användare",
  "Observera att vi kan komma att överföra, lagra och behandla dina personuppgifter utanför det land där du bor. Dina personuppgifter behandlas också av personal och externa tjänsteleverantörer (tredje part) och partners i dessa länder.",
  "Om vi överför dina personuppgifter ut ur Europa kommer vi att förlita oss på erkända överföringsmekanismer, till exempel Europeiska kommissionens standardavtalsklausuler, eller likvärdiga avtal från relevant behörig myndighet i Storbritannien (beroende på vad som är relevant) såvida inte dataöverföringen sker till ett land som bedömts säkerställer en adekvat skyddsnivå.",
  "## Kontakt",
  "Om du har frågor om våra integritetsrutiner eller denna integritetspolicy, eller om du vill utöva några av dina rättigheter, ring eller skicka e-post till oss på info@kornu.se, alternativt kan du kontakta oss på F O Petersons Gata 6, 421 31 Västra Frölunda, Sverige.",
  "När det gäller tillämplig dataskyddslagstiftning, och om inget annat uttryckligen anges, är vi personuppgiftsansvarig för dina personuppgifter."
];

export const contactInformationParagraphs: string[] = [
  "Telefonummer: 031 386 00 86\nEpost: info@kornu.se"
];

export const userTermsParagraphs: string[] = [
  "## §1 Avtal",
  "När kund köper, bokar, anmäler sig eller skriver in sig, antingen själv eller via trafikskolans personal, ingås avtal med trafikskolan och kunden samtycker till dessa allmänna villkor.",
  "## §2 Minderårig",
  "En kund som är under 18 år måste enligt lag ha sina föräldrars eller förmyndares samtycke för att ingå avtal med trafikskolan. Om samtycke inte kan ske på annat godtagbart sätt ska kunden uppvisa ett intyg från sina föräldrar eller förmyndare. Trafikskolan dokumenterar hur kunden har identifierat sig.",
  "## §3 Dataskyddsförordningen (GDPR)",
  "Dataskyddsförordningen (General Data Protection Regulation) gäller som lag i alla EU:s medlemsländer från och med den 25 maj 2018. Förordningen reglerar trafikskolans användning av kunds personuppgifter och stärker rättigheterna för kunden när det gäller personlig integritet. Denna paragraf handlar om hur trafikskolan tillämpar denna förordning.",
  "## Personuppgifter vid försäljning",
  "Trafikskolan lagrar namn och adress som krävs för att skapa ett korrekt kvitto enligt bokföringslagens krav på en kontantfaktura. E-post lagras för att kunna sända kvitto till kunden. Uppgifterna lagras i sju år innan de raderas.",
  "## Personuppgifter vid utbildning",
  "Trafikskolan sparar namn, adress, telefonnummer, personnummer enligt trafikförordningens krav på trafikskolan. E-post lagras för att kunna sända lektionstider till kunden. Kunden loggar även in i sitt läromedel med sin e-postadress. Uppgifter om utbildningen lagras för att kunna genomföra en utbildning i enlighet med Transportstyrelsens krav på utbildningsplan och dokumentation. Vi lagrar inga känsliga uppgifter i samband med utbildningen, utöver personnummer, som till exempel personuppgifter som avslöjar etniskt ursprung, politiska åsikter, religiös eller filosofisk övertygelse eller uppgifter om sexualliv,  hälsa, t ex ADHD. Om du går på en anpassad utbildning, t ex för dyslexi, lagras information om detta.",
  "## Behandling av personuppgifter",
  "Personuppgifter hanteras endast av trafikskolans personal, myndighetsperson vid eventuell tillsyn samt eventuellt underleverantörer med speciella avtal, som ansvarar för datasystem eller liknande. Uppgifterna delas aldrig med någon övrig tredje part utan samtycke.",
  "## Samtycke till lagring av personuppgifter",
  "Inhämtning av samtycke till lagring av personuppgifter sker i enlighet med §1. Trafikskolan dokumenterar hur kunden har samtyckt. I samband med utskick av information, marknadsföring, från trafikskola till kund kan kund ange att man inte önskar denna typ av utskick. Obligatoriska utskick, t ex lektionstider och kvitton, kan inte väljas bort.",
  "## Utdrag av personuppgifter",
  "Kund kan begära att få ett utdrag av vad som finns lagrat om kunden. Trafikskolan ska då skyndsamt till kunden skapa en PDF med denna information.",
  "## Begäran om ändring av personuppgifter",
  "Kund kan begära att trafikskolan ändrar lagrade personuppgifter. Kund ska då tala om för trafikskolan vad som ska ändras. Trafikskolan ska då skyndsamt ändra personuppgifterna. Om någon personuppgift inte går att ändra på grund av rättsliga krav kommer kunden att få besked om detta.",
  "## Begäran om radering av personuppgifter",
  "Kund kan begära att trafikskolan raderar lagrade personuppgifter. Trafikskolan kommer då att skyndsamt radera uppgifterna. Om någon personuppgift inte går att radera på grund av rättsliga krav kommer kunden att få besked om detta.",
  "## Kund ändrar någon av sina tidigare uppgivna personuppgifter",
  "Kund ska alltid informera trafikskolan vid byte av adress, telefonnummer eller e-postadress under aktiv utbildning. Om trafikskolan behöver meddela kunden viktig information och inte får kontakt via angivna kontaktuppgifter kan trafikskolan inte hållas ansvarig för detta.",
  "## Säkerhet vid lagring av personuppgifter",
  "All data lagras på säkra servers inom EU som sköts av Trafikskola Online AB och dess underleverantör Microsoft Azure som är certifierat av ISO 27018. Trafikskola Online jobbar aktivt för hög säkerhet kring de personuppgifter som lagras. Endast personal som har speciella avtal har möjlighet att hantera trafikskolans uppgifter.",
  "## Incidenter med personuppgifter",
  "Om trafikskolan utsätts för intrång eller någon enhet förloras vid t ex stöld nollställs omgående enhetens inloggningsuppgifter. Inga data lagras på enheten. Vid omfattande dataintrång i systemet finns rutiner för att undersöka och säkerställa en fortsatt hög säkerhet. Vissa uppgifter, t ex lösenordet, är krypterade.",
  "Trafikskolan lagrar inte uppgifter av den typ som gör att ett dataintrång medför risker för enskildas fri- och rättigheter och behöver därför inte anmälas till tillsynsmyndighet inom 72 timmar.",
  "## §4 Bokningsregler",
  "## Regler för bokningar utan egen inloggning via trafikskolans E-handel",
  "En bokning och/eller reservation som är gjord via e-handel är bindande.",
  "Av- eller ombokning av bokade tider måste ske senast klockan 13 vardagen innan bokad tid. Vid senare av- eller ombokning debiteras fullt avgift. Av- eller ombokning senare än 48 timmar innan bokad tid debiteras halv avgift.",
  "Vid förhållande man inte kan råda över, t ex akut sjukdom, debiteras ingen avgift vid uppvisande av sjukintyg. Av- eller ombokning kan endast göras via telefon.",
  "## Regler för bokningar med egen inloggning via trafikskolans Läromedel",
  "En bokning som är gjord via läromedel eller trafikskolans personal är bindande.",
  "Av- eller ombokning av bokade tider måste ske senast klockan 13 vardagen innan bokad tid. Vid senare av- eller ombokning debiteras fullt avgift.",
  "Vid förhållande man inte kan råda över, t ex akut sjukdom, debiteras ingen avgift vid uppvisande av sjukintyg.",
  "## §5 Köp och priser",
  "Minderåriga (under 18 år) får ej genomföra köp utan målsmans godkännande. Återbetalning vid förskottsbetalning sker mot avgift på 10% av beloppet under förutsättning att övriga regler kring exempelvis avbokning har följts.",
  "Aktuella priser redovisas på trafikskolans webbplatser. Priserna kan ändras under utbildningens gång. Ibland krävs förskottsbetalning för att priset ska gälla. Alla priser är i SEK inklusive moms.",
  "Köpt tjänst, i form av exempelvis paket, är giltigt till samma pris i 1 år från inköpsdatum.",
  "## Direktbetalning, särskilda regler vid direktbetalning via Läromedel eller E-handel",
  "Direktbetalning av testlektioner och kurser samt insättning på elevsaldo via webben sker med Swish. Vid godkänd betalning sänds en bekräftelse av trafikskolan till en av köparen angiven e-postadress.",
  "## Reservation, särskilda regler vid reservation via Läromedel eller E-handel",
  "En kund kan reservera en tid mot en extra avgift på 50 kr.",
  "Betalning kan därefter göras på plats på trafikskolan innan eller på bokad datum. Betalning kan då ske med kort (MasterCard/Visa) eller Swish.",
  "Om det är mer än 3 vardagar kvar till kursen/lektionen kan betalning av reservationen även ske via bankgiro X eller till Swish X. Efter betalning av priset för kursen/lektionen plus 50 kr ska köparen sända trafikskolan ett e-postmeddelande till X med namn, vad som bokats, referensnummer, belopp samt hur detta har betalats. Vid godkänd betalning sänds en bekräftelse av trafikskolan till en av köparen angiven e-postadress.",
  "## §6 Personligt användarkonto för utbildning",
  "En kund som skrivs in på skolan som elev kan få ett användarkonto med möjlighet att nyttja bland annat trafikskolans läromedel. Användarkontot är personligt. Inloggning & lösenord ska endast användas av den elev det är avsett för. Eleven har ansvar för att välja ett säkert lösenord och skydda detta. Trafikskolan är inte ansvarig för eventuell skada som uppstår om någon utomstående loggar in och använder elevens konto.",
  "I regel gäller fritt personligt bruk av trafikskolans tjänster när användarkontot är aktivt. Detta förutsätter dock att bruket faller inom ramen för vad som kan anses vara rimligt för en elev, dess handledare och trafiklärare. Trafikskolan förbehåller sig rätten att stänga av kontot om det överskrider gränsen för rimligt bruk. Vid stängning av konto ska trafikskolan informera eleven, via av eleven angiven e-postadress, på vilket sätt man överskridit gränsen för bruk. Finns det en adekvat förklaring till den höga brukandegraden kan användarkontot återaktiveras.",
  "## §7 Upphovsrätt och nyttjanderätt",
  "Allt material på trafikskolans webbplatser är skyddat av lagen om upphovsrätt. Materialet får endast användas för privat bruk i samband med att man använder tjänsten. Det är inte tillåtet att kopiera, överlåta, hyra ut, ändra, vidaresälja eller på annat vis använda materialet på ett kommersiellt eller icke kommersiellt sätt.",
  "## §8 Friskrivning från ansvar",
  "Trafikskolan tar inte ansvar för avgifter som kan tillkomma vid påminnelse eller inkassokrav om eleven ej uppgett korrekta uppgifter, detta gäller även elevens e-postadress.",
  "## §9 Ändringar av dessa villkor",
  "Allmänna villkor och köpevillkor kan komma att ändras under utbildningen. Trafikskolan ska informera eleven om eventuella ändringar. Allmänna villkor publiceras alltid på vår webbplats. Köpevillkoren visas alltid i samband med bokning eller köp.",
  "## §10 Tvister",
  "Trafikskolan ska göra allt man kan för att man som elev ska bli nöjd. Som elev har man ett ansvara att följa de regler som finns.",
  "Vid tvister gäller svensk lag för trafikskolans anmälnings- och köpevillkor. Tvister som avser giltighet, tolkning och tillämpning ska avgöras i första hand med hjälp av \"Allmänna reklamationsnämnden\" och i andra hand, i allmän domstol, varvid närmaste tingsrätt ska vara första instans.",
  "## §11 Trafikskolans uppgifter",
  "Kör Nu Trafikskola AB\nF O Petersons gata 6\n421 31 Västra Frölunda\nTelefon: 0313860086\nE-post: info@kornu.se\nOrganisationsnummer: 559288-1386\nBankgiro: 5658-0657\nSwish : 123-200 96 11\nBank: Svea Bank\nInnehar F-skattebevis"
];

export const shippingPolicyParagraphs: string[] = [
  "Körkorts utbildning, vi kontaktar dig för bokning efter du beställt\nKvitto levereras på epost"
];

export const legalNoticeParagraphs: string[] = [
  "## §1 Avtal",
  "När kund köper, bokar, anmäler sig eller skriver in sig, antingen själv eller via trafikskolans personal, ingås avtal med trafikskolan och kunden samtycker till dessa allmänna villkor.",
  "## §2 Minderårig",
  "En kund som är under 18 år måste enligt lag ha sina föräldrars eller förmyndares samtycke för att ingå avtal med trafikskolan. Om samtycke inte kan ske på annat godtagbart sätt ska kunden uppvisa ett intyg från sina föräldrar eller förmyndare. Trafikskolan dokumenterar hur kunden har identifierat sig.",
  "## §3 Dataskyddsförordningen (GDPR)",
  "Dataskyddsförordningen (General Data Protection Regulation) gäller som lag i alla EU:s medlemsländer från och med den 25 maj 2018. Förordningen reglerar trafikskolans användning av kunds personuppgifter och stärker rättigheterna för kunden när det gäller personlig integritet. Denna paragraf handlar om hur trafikskolan tillämpar denna förordning.",
  "## Personuppgifter vid försäljning",
  "Trafikskolan lagrar namn och adress som krävs för att skapa ett korrekt kvitto enligt bokföringslagens krav på en kontantfaktura. E-post lagras för att kunna sända kvitto till kunden. Uppgifterna lagras i sju år innan de raderas.",
  "## Personuppgifter vid utbildning",
  "Trafikskolan sparar namn, adress, telefonnummer, personnummer enligt trafikförordningens krav på trafikskolan. E-post lagras för att kunna sända lektionstider till kunden. Kunden loggar även in i sitt läromedel med sin e-postadress. Uppgifter om utbildningen lagras för att kunna genomföra en utbildning i enlighet med Transportstyrelsens krav på utbildningsplan och dokumentation. Vi lagrar inga känsliga uppgifter i samband med utbildningen, utöver personnummer, som till exempel personuppgifter som avslöjar etniskt ursprung, politiska åsikter, religiös eller filosofisk övertygelse eller uppgifter om sexualliv,  hälsa, t ex ADHD. Om du går på en anpassad utbildning, t ex för dyslexi, lagras information om detta.",
  "## Behandling av personuppgifter",
  "Personuppgifter hanteras endast av trafikskolans personal, myndighetsperson vid eventuell tillsyn samt eventuellt underleverantörer med speciella avtal, som ansvarar för datasystem eller liknande. Uppgifterna delas aldrig med någon övrig tredje part utan samtycke.",
  "## Samtycke till lagring av personuppgifter",
  "Inhämtning av samtycke till lagring av personuppgifter sker i enlighet med §1. Trafikskolan dokumenterar hur kunden har samtyckt. I samband med utskick av information, marknadsföring, från trafikskola till kund kan kund ange att man inte önskar denna typ av utskick. Obligatoriska utskick, t ex lektionstider och kvitton, kan inte väljas bort.",
  "## Utdrag av personuppgifter",
  "Kund kan begära att få ett utdrag av vad som finns lagrat om kunden. Trafikskolan ska då skyndsamt till kunden skapa en PDF med denna information.",
  "## Begäran om ändring av personuppgifter",
  "Kund kan begära att trafikskolan ändrar lagrade personuppgifter. Kund ska då tala om för trafikskolan vad som ska ändras. Trafikskolan ska då skyndsamt ändra personuppgifterna. Om någon personuppgift inte går att ändra på grund av rättsliga krav kommer kunden att få besked om detta.",
  "## Begäran om radering av personuppgifter",
  "Kund kan begära att trafikskolan raderar lagrade personuppgifter. Trafikskolan kommer då att skyndsamt radera uppgifterna. Om någon personuppgift inte går att radera på grund av rättsliga krav kommer kunden att få besked om detta.",
  "## Kund ändrar någon av sina tidigare uppgivna personuppgifter",
  "Kund ska alltid informera trafikskolan vid byte av adress, telefonnummer eller e-postadress under aktiv utbildning. Om trafikskolan behöver meddela kunden viktig information och inte får kontakt via angivna kontaktuppgifter kan trafikskolan inte hållas ansvarig för detta.",
  "## Säkerhet vid lagring av personuppgifter",
  "All data lagras på säkra servers inom EU som sköts av Trafikskola Online AB och dess underleverantör Microsoft Azure som är certifierat av ISO 27018. Trafikskola Online jobbar aktivt för hög säkerhet kring de personuppgifter som lagras. Endast personal som har speciella avtal har möjlighet att hantera trafikskolans uppgifter.",
  "## Incidenter med personuppgifter",
  "Om trafikskolan utsätts för intrång eller någon enhet förloras vid t ex stöld nollställs omgående enhetens inloggningsuppgifter. Inga data lagras på enheten. Vid omfattande dataintrång i systemet finns rutiner för att undersöka och säkerställa en fortsatt hög säkerhet. Vissa uppgifter, t ex lösenordet, är krypterade.",
  "Trafikskolan lagrar inte uppgifter av den typ som gör att ett dataintrång medför risker för enskildas fri- och rättigheter och behöver därför inte anmälas till tillsynsmyndighet inom 72 timmar.",
  "## §4 Bokningsregler",
  "## Regler för bokningar utan egen inloggning via trafikskolans E-handel",
  "En bokning och/eller reservation som är gjord via e-handel är bindande.",
  "Av- eller ombokning av bokade tider måste ske senast klockan 13 vardagen innan bokad tid. Vid senare av- eller ombokning debiteras fullt avgift. Av- eller ombokning senare än 48 timmar innan bokad tid debiteras halv avgift.",
  "Vid förhållande man inte kan råda över, t ex akut sjukdom, debiteras ingen avgift vid uppvisande av sjukintyg. Av- eller ombokning kan endast göras via telefon.",
  "## Regler för bokningar med egen inloggning via trafikskolans Läromedel",
  "En bokning som är gjord via läromedel eller trafikskolans personal är bindande.",
  "Av- eller ombokning av bokade tider måste ske senast klockan 13 vardagen innan bokad tid. Vid senare av- eller ombokning debiteras fullt avgift.",
  "Vid förhållande man inte kan råda över, t ex akut sjukdom, debiteras ingen avgift vid uppvisande av sjukintyg.",
  "## §5 Köp och priser",
  "Minderåriga (under 18 år) får ej genomföra köp utan målsmans godkännande. Återbetalning vid förskottsbetalning sker mot avgift på 10% av beloppet under förutsättning att övriga regler kring exempelvis avbokning har följts.",
  "Aktuella priser redovisas på trafikskolans webbplatser. Priserna kan ändras under utbildningens gång. Ibland krävs förskottsbetalning för att priset ska gälla. Alla priser är i SEK inklusive moms.",
  "Köpt tjänst, i form av exempelvis paket, är giltigt till samma pris i 1 år från inköpsdatum.",
  "## Direktbetalning, särskilda regler vid direktbetalning via Läromedel eller E-handel",
  "Direktbetalning av testlektioner och kurser samt insättning på elevsaldo via webben sker med Swish. Vid godkänd betalning sänds en bekräftelse av trafikskolan till en av köparen angiven e-postadress.",
  "## Reservation, särskilda regler vid reservation via Läromedel eller E-handel",
  "En kund kan reservera en tid mot en extra avgift på 50 kr.",
  "Betalning kan därefter göras på plats på trafikskolan innan eller på bokad datum. Betalning kan då ske med kort (MasterCard/Visa) eller Swish.",
  "Om det är mer än 3 vardagar kvar till kursen/lektionen kan betalning av reservationen även ske via bankgiro X eller till Swish X. Efter betalning av priset för kursen/lektionen plus 50 kr ska köparen sända trafikskolan ett e-postmeddelande till X med namn, vad som bokats, referensnummer, belopp samt hur detta har betalats. Vid godkänd betalning sänds en bekräftelse av trafikskolan till en av köparen angiven e-postadress.",
  "## §6 Personligt användarkonto för utbildning",
  "En kund som skrivs in på skolan som elev kan få ett användarkonto med möjlighet att nyttja bland annat trafikskolans läromedel. Användarkontot är personligt. Inloggning & lösenord ska endast användas av den elev det är avsett för. Eleven har ansvar för att välja ett säkert lösenord och skydda detta. Trafikskolan är inte ansvarig för eventuell skada som uppstår om någon utomstående loggar in och använder elevens konto.",
  "I regel gäller fritt personligt bruk av trafikskolans tjänster när användarkontot är aktivt. Detta förutsätter dock att bruket faller inom ramen för vad som kan anses vara rimligt för en elev, dess handledare och trafiklärare. Trafikskolan förbehåller sig rätten att stänga av kontot om det överskrider gränsen för rimligt bruk. Vid stängning av konto ska trafikskolan informera eleven, via av eleven angiven e-postadress, på vilket sätt man överskridit gränsen för bruk. Finns det en adekvat förklaring till den höga brukandegraden kan användarkontot återaktiveras.",
  "## §7 Upphovsrätt och nyttjanderätt",
  "Allt material på trafikskolans webbplatser är skyddat av lagen om upphovsrätt. Materialet får endast användas för privat bruk i samband med att man använder tjänsten. Det är inte tillåtet att kopiera, överlåta, hyra ut, ändra, vidaresälja eller på annat vis använda materialet på ett kommersiellt eller icke kommersiellt sätt.",
  "## §8 Friskrivning från ansvar",
  "Trafikskolan tar inte ansvar för avgifter som kan tillkomma vid påminnelse eller inkassokrav om eleven ej uppgett korrekta uppgifter, detta gäller även elevens e-postadress.",
  "## §9 Ändringar av dessa villkor",
  "Allmänna villkor och köpevillkor kan komma att ändras under utbildningen. Trafikskolan ska informera eleven om eventuella ändringar. Allmänna villkor publiceras alltid på vår webbplats. Köpevillkoren visas alltid i samband med bokning eller köp.",
  "## §10 Tvister",
  "Trafikskolan ska göra allt man kan för att man som elev ska bli nöjd. Som elev har man ett ansvara att följa de regler som finns.",
  "Vid tvister gäller svensk lag för trafikskolans anmälnings- och köpevillkor. Tvister som avser giltighet, tolkning och tillämpning ska avgöras i första hand med hjälp av \"Allmänna reklamationsnämnden\" och i andra hand, i allmän domstol, varvid närmaste tingsrätt ska vara första instans.",
  "## §11 Trafikskolans uppgifter",
  "Kör Nu Trafikskola AB\nF O Petersons gata 6\n421 31 Västra Frölunda\nTelefon: 0313860086\nE-post: info@kornu.se\nOrganisationsnummer: 559288-1386\nBankgiro: 5658-0657\nSwish : 123-200 96 11\nBank: Svea Bank\nInnehar F-skattebevis"
];

export const refundPolicyParagraphs: string[] = [
  "Återbetalning vid förskottsbetalning sker mot avgift på 10% av beloppet under förutsättning att övriga regler kring exempelvis avbokning har följts."
];
